name: query
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
  - r
dependencies:
  - r-base>=4.1
  - r-devtools=2.4.5
  - r-coloc>=5.1
  - notebook 
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - r-rcppeigen>=0.3.3.9.1
  - mpfr
  - r-gmp
  - r-arrangements
  - r-duckdb
  - r-arrow 
  - rpy2
