name: BIOL8803
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=>4.1
  - r-coloc>=5.1
  - notebook 
  - r-irkernel
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - r-languageserver
